### ISSUE TITLE
Status of GlobalSplineFit?

### ISSUE THREAD

**Issue by niess** [afedynitch/MCEq#31]
Hello,

first of all thank you for sharing this great tool :)

My issue concern the GlobalSplineFit. What is the current status? Is it usable as so. My concerns are the following:

- There are two classes: GlobalSplineFit and GlobalSplineFitBeta, the "Beta" suggesting that it is experimental (?)

- When using GlobalSplineFit I get the following error:
  ```
  File ".../crflux/models.py", line 898, in __init__
      from gsf.flux import z_to_a
  ModuleNotFoundError: No module named 'gsf'
  ```
  Maybe I need to install an optional package for this work? Which one? From PyPI?

- When using GlobalSplineFitBeta with no args it runs without error but I don't seem to get the expected result. 

I tried to reproduce the results of [arXiv:1908.08365](https://arxiv.org/abs/1909.08365) using `GlobalSplineFitBeta` but failed. I set up a [temporary repo](https://github.com/niess/check-mod-pprod) illustrating how I proceed. Comparing to BESS-TeV data with a cosine of 0.95 the computed flux is lower at high energies than what is shown in the paper while applying the Barr like correction factors of table 2 (see e.g. the [generated pdf](https://github.com/niess/check-mod-pprod/blob/master/flux.pdf) to be compared with the left side of figure 2 in the 2019 paper for a cosine of 0.95). 

I tried to use another primary model as cross-check: `crf.HillasGaisser2013, 'H3a'`. Then I get a better agreement with BESS-TeV at high energies but a too low flux at lower energies. Therefore I am suspecting that I might not use the same GSF model than in the 2019 paper?

But maybe I am missing some other setting(s)?

**Comment by afedynitch** [comment]
Hi Valentin,

thanks for your carefully working out your case.
 
- Beta suggests that it is not final
- the gsf package is not publicly available, but we re-started work on it very recently, so stay tuned
- GlobalSplineFitBeta should run fine. By expected result, you mean the BESS-TeV example below?

It is not about the settings. One of the important points is the big covariance matrix in Figure 3 of the proceedings. The experimental data is allowed to move within its systematic uncertainties. Your observation means that the systematic parameters of BESS have been pulled by the fit to move the data down, and bring it in agreement with the model and the other data sets (within their systematics). This is not so easy to reproduce because you need the systematic functions, and the global fit. While we want to make this piece of technology publicly available at some point, it is too early right now. 

We have worked on this project in the meantime and will present an update of it, or the final result, at the upcoming ICRC2021. GSF is not as preliminary as the muon fit and stable. It's just falling of the table at the moment...

**Comment by niess** [comment]
Hello Anatoli,

thank you. I missed this part about the covariance matrix. It makes sense indeed to let data float as well. So, if I understand properly on figure 2 of the 2019 paper the BESS-TeV data have been moved within their systematics which would explain the discrepancy that I observed?

I am looking forward to the updated results :)

Meanwhile I'd like to use the 2019 results if possible? Is it correct for this purpose to use the current `GlobalSplineFitBeta` with the following MCEq settings:

```python
mceq = MCEqRun(
    interaction_model='SIBYLL23C',
    primary_model = (crf.GlobalSplineFitBeta, None),
    density_model = ('MSIS00', ('Tokyo', 'October')),  # <= Those might change
    theta_deg = 0                                      #  depending on the observation
)

def weight(xmat, egrid, name, c):
    return (1 + c) * numpy.ones_like(xmat)

mceq.set_mod_pprod(2212,  211, weight, ('a', 0.141)) # Coefficients taken
mceq.set_mod_pprod(2212, -211, weight, ('a', 0.116)) # from table 2 of Yanez et
mceq.set_mod_pprod(2212,  321, weight, ('a', 0.402)) # al.
mceq.set_mod_pprod(2212, -321, weight, ('a', 0.583))
mceq.regenerate_matrices(skip_decay_matrix=True)
```

**Comment by afedynitch** [comment]
Yes, the difference between your result and Fig.2 should be explained by this. There are some more changes that may result in some differences, like:
- the changes from pre-V1.2 MCEq to the current one ([see here](https://mceq.readthedocs.io/en/latest/v12v11_diff.html)).
- We also found some feature in the fitter that would produce slightly different results compared to your weight function.
 
As you can see from your comparison with BESS at lower energies, where it has small errors, the result is ok. So as working hypothesis you can use your present approach and update it later in the summer.

**Comment by niess** [comment]
Thank you. Then I'll use those settings meanwhile. The decay tables bug might have on impact on the fit indeed. I am curious to see the new fit results this summer.
