### ISSUE TITLE
Definition of prompt particles

### ISSUE THREAD

**Issue by The-Ludwig** [afedynitch/MCEq#49]
Hi,
for my master thesis I am looking into prompt atmospheric particles. MCEq is of great help in that!
Prompt particles are defined in MCEq as
```python
#: Definition of prompt: default ctau < 0.123 cm (that of D0)
prompt_ctau = 0.123
```
But the `ctau` value of D0 is `0.0123cm`:
```python
from particle import Particle
import pint
u = pint.UnitRegistry()
print((Particle.from_name("D0").lifetime * u('ns') *u('c')).to('cm'))
# Output: 0.012294515916467444 centimeter
```

Is the `prompt_ctau` value wrong or is it purposefully 10 times larger and the description should be `(that of D0*10)`?

**Comment by afedynitch** [comment]
Hi!

Thanks for pointing this out. Indeed the docs is a bit misleading on this. The value only defines what will be counted as prompt and conventional in the output and there is no impact on physics. Everything with ctau < than that is pr_ otherwise conv_. Between K0S and D mesons  there are no other particles that would be ambiguous in counting. 

In the upcoming version, [I rephrased this in the config of the upcoming version](https://github.com/afedynitch/MCEq/blob/e5b5b2f8f4b81ae80af6d4d10f31ca2016e8cd51/mceq_config.py#L49). Hope it clarifies your question. In that case feel free to close the issue.

**Comment by The-Ludwig** [comment]
Hi,
perfect, thanks a lot for clarification on this! :+1:
